services:
  user-shard-1-node-1:
    image: bitnami/postgresql-repmgr:14
    ports:
      - "5432"
    env_file:
      - ../.env
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRES_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=user-shard-1-node-1
      - REPMGR_PARTNER_NODES=user-shard-1-node-1,user-shard-1-node-2,user-shard-1-node-3
      - REPMGR_NODE_NAME=user-shard-1-node-1
      - REPMGR_NODE_NETWORK_NAME=user-shard-1-node-1
    volumes:
      - user_shard_1_node_1:/bitnami/postgresql
      - ./create_extensions.sql:/docker-entrypoint-initdb.d/create_extensions.sql:ro
    networks:
      - user-storage-network

  user-shard-1-node-2:
    image: bitnami/postgresql-repmgr:14
    ports:
      - "5432"
    env_file:
      - ../.env
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRES_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=user-shard-1-node-1
      - REPMGR_PARTNER_NODES=user-shard-1-node-1,user-shard-1-node-2,user-shard-1-node-3
      - REPMGR_NODE_NAME=user-shard-1-node-2
      - REPMGR_NODE_NETWORK_NAME=user-shard-1-node-2
    volumes:
      - user_shard_1_node_2:/bitnami/postgresql
      - ./create_extensions.sql:/docker-entrypoint-initdb.d/create_extensions.sql:ro
    networks:
      - user-storage-network
  
  user-shard-1-node-3:
    image: bitnami/postgresql-repmgr:14
    ports:
      - "5432"
    env_file:
      - ../.env
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRES_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=user-shard-1-node-1
      - REPMGR_PARTNER_NODES=user-shard-1-node-1,user-shard-1-node-2,user-shard-1-node-3
      - REPMGR_NODE_NAME=user-shard-1-node-3
      - REPMGR_NODE_NETWORK_NAME=user-shard-1-node-3
    volumes:
      - user_shard_1_node_3:/bitnami/postgresql
      - ./create_extensions.sql:/docker-entrypoint-initdb.d/create_extensions.sql:ro
    networks:
      - user-storage-network

  user-shard-1-node-1_exporter-1:
    image: prometheuscommunity/postgres-exporter:v0.11.1
    command: --log.level=debug
    environment:
      DATA_SOURCE_URI: "user-shard-1-node-1:5432/habrdb?sslmode=disable"
      DATA_SOURCE_USER: habrpguser
      DATA_SOURCE_PASS: pgpwd4habr
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    volumes:
      - ./queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - "9187"
    networks:
      - user-storage-network
    restart: unless-stopped
    depends_on:
      - user-shard-1-node-1

  user-shard-1-node-2_exporter-2:
    image: prometheuscommunity/postgres-exporter:v0.11.1
    command: --log.level=debug
    environment:
      DATA_SOURCE_URI: "user-shard-1-node-2:5432/habrdb?sslmode=disable"
      DATA_SOURCE_USER: habrpguser
      DATA_SOURCE_PASS: pgpwd4habr
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    volumes:
      - ./queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - "9187"
    networks:
      - user-storage-network
    restart: unless-stopped
    depends_on:
      - user-shard-1-node-2
  
  user-shard-1-node-3_exporter-3:
    image: prometheuscommunity/postgres-exporter:v0.11.1
    command: --log.level=debug
    environment:
      DATA_SOURCE_URI: "user-shard-1-node-3:5432/habrdb?sslmode=disable"
      DATA_SOURCE_USER: habrpguser
      DATA_SOURCE_PASS: pgpwd4habr
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    volumes:
      - ./queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - "9187"
    networks:
      - user-storage-network
    restart: unless-stopped
    depends_on:
      - user-shard-1-node-3

volumes:
  user_shard_1_node_1:
  user_shard_1_node_2:
  user_shard_1_node_3: