// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AddProductToShelfInput struct {
	ShelfID           string  `json:"shelfId"`
	ProductID         string  `json:"productId"`
	AllocatedCapacity float64 `json:"allocatedCapacity"`
}

type CreateProductInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	PreviewURL  *string `json:"previewUrl,omitempty"`
	Visibility  *bool   `json:"visibility,omitempty"`
}

type CreateRackInput struct {
	WarehouseID string `json:"warehouseId"`
	Aisle       string `json:"aisle"`
}

type CreateShelfInput struct {
	RackID      string  `json:"rackId"`
	Level       int32   `json:"level"`
	Priority    int32   `json:"priority"`
	MaxCapacity float64 `json:"maxCapacity"`
}

type CreateWarehouseInput struct {
	Name     string `json:"name"`
	Location string `json:"location"`
	Address  string `json:"address"`
}

type File struct {
	ID      string   `json:"id"`
	Product *Product `json:"product"`
	URL     string   `json:"url"`
}

type Mutation struct {
}

type Product struct {
	ID            string          `json:"id"`
	PreviewURL    *string         `json:"previewUrl,omitempty"`
	Name          string          `json:"name"`
	Description   *string         `json:"description,omitempty"`
	Price         int32           `json:"price"`
	CreatedAt     time.Time       `json:"createdAt"`
	Visibility    bool            `json:"visibility"`
	Files         []*File         `json:"files"`
	Reviews       []*Review       `json:"reviews"`
	Tags          []*Tag          `json:"tags"`
	ShelfProducts []*ShelfProduct `json:"shelfProducts"`
}

type Query struct {
}

type Rack struct {
	ID        string     `json:"id"`
	Warehouse *Warehouse `json:"warehouse"`
	Aisle     string     `json:"aisle"`
	Shelves   []*Shelf   `json:"shelves"`
}

type Review struct {
	ID          string    `json:"id"`
	Login       string    `json:"login"`
	Grade       int32     `json:"grade"`
	Description *string   `json:"description,omitempty"`
	Product     *Product  `json:"product"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Shelf struct {
	ID           string          `json:"id"`
	Rack         *Rack           `json:"rack"`
	Level        int32           `json:"level"`
	Priority     int32           `json:"priority"`
	MaxCapacity  float64         `json:"maxCapacity"`
	UsedCapacity float64         `json:"usedCapacity"`
	Products     []*ShelfProduct `json:"products"`
}

type ShelfProduct struct {
	ID                string   `json:"id"`
	Shelf             *Shelf   `json:"shelf"`
	Product           *Product `json:"product"`
	AllocatedCapacity float64  `json:"allocatedCapacity"`
}

type Tag struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Products []*Product `json:"products"`
}

type Warehouse struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Location string  `json:"location"`
	Address  string  `json:"address"`
	Racks    []*Rack `json:"racks"`
}
