services:
  migrate-user:
    image: migrator
    environment:
      - TYPE_DB=postgres
      - URLS=postgresql://postgres:postgres@user-haproxy:5000/postgres?sslmode=disable,postgresql://postgres:postgres@user-haproxy:5002/postgres?sslmode=disable
    networks:
      - storage-network
    volumes:
      - ./sql/deploy:/app/sql
    depends_on:
      user-haproxy:
        condition: service_healthy