services:
  geo_pgadmin:
    container_name: geo_pgadmin
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - qwik-network
      - user-storage-network