FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app
COPY --from=build /app .
COPY --from=build /src/sql ./sql
COPY --from=build /src/Storage/Postgres/InitHistoryTable.sql .
ENTRYPOINT ["dotnet", "DbNomad.dll"]