services:
  migrate-warehouse:
    image: migrator
    environment:
      - TYPE_DB=postgres
      - URLS=postgresql://warehouse_nmz6_user:v4IB0zklBdt0SEUydaBkFBktpZc039Qb@dpg-d76dokvpm1nc7393s3mg-a.oregon-postgres.render.com/warehouse_nmz6
    networks:
      - storage-network
    volumes:
      - ./sql/deploy:/app/sql
    depends_on:
      warehouse-haproxy:
        condition: service_healthy