include:
  - storage/postgres/compose.user-pg.yml
  - storage/redis/compose.user-redis.yml

services:
  user:
    build:
      context: ./service
      dockerfile: dockerfile
    ports:
      - "8080"
    depends_on:
      user-pgpool-shard-0:
        condition: service_healthy
      user-pgpool-shard-1:
        condition: service_healthy
    networks:
      - qwik-network
    deploy:
      replicas: 4