include:
  - storage/postgres/haproxy/compose.user-haproxy.yml
  - storage/postgres/migrations/compose.migrations.yml
  - storage/postgres/patroni/shard1/compose.user-patroni.yml
  - storage/postgres/patroni/shard2/compose.user-patroni.yml
  - storage/postgres/zookeeper/compose.user-zookeeper.yml

  - storage/redis/compose.user-redis.yml

services:
  user:
    build:
      context: ./service
      dockerfile: dockerfile
    ports:
      - "8080"
    depends_on:
      - user-haproxy
    networks:
      - qwik-network
    deploy:
      replicas: 4
