services:
  redis:
    image: redis:latest
    container_name: user-redis
    ports:
      - "6379"
    env_file:
      - .env
    volumes:
      - user-redis-data:/data
    networks:
      - qwik-network
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  user-redis-data: