include:
  - migrations/compose.migrations.yml
  - shards/shard0/compose.user-shard-pg0.yml
  - shards/shard1/compose.user-shard-pg1.yml

services:
  user-pgpool-shard-0:
    image: bitnami/pgpool:4
    ports:
      - "5432"
    environment:
      - PGPOOL_BACKEND_NODES=0:user-shard-0-node-1:5432,1:user-shard-0-node-2:5432,2:user-shard-0-node-3:5432
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=hvou4nuj4YVYmKuwDWIrO8wVzgfvtU6b
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=sdpvaklslknbkldzmb
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
      - PGPOOL_FAILOVER_ON_BACKEND_ERROR=on
      - PGPOOL_HEALTH_CHECK_PERIOD=10
      - PGPOOL_SR_CHECK_PERIOD=10
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_ENABLE_STATEMENT_LOAD_BALANCING=yes
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - user-shard-0-node-1
      - user-shard-0-node-2
      - user-shard-0-node-3
    networks:
      - user-storage-network
      - qwik-network

  user-pgpool-shard-1:
    image: bitnami/pgpool:4
    ports:
      - "5432"
    environment:
      - PGPOOL_BACKEND_NODES=0:user-shard-1-node-1:5432,1:user-shard-1-node-2:5432,2:user-shard-1-node-3:5432
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=hvou4nuj4YVYmKuwDWIrO8wVzgfvtU6b
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=sdpvaklslknbkldzmb
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
      - PGPOOL_FAILOVER_ON_BACKEND_ERROR=on
      - PGPOOL_HEALTH_CHECK_PERIOD=10
      - PGPOOL_SR_CHECK_PERIOD=10
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_ENABLE_STATEMENT_LOAD_BALANCING=yes
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - user-shard-1-node-1
      - user-shard-1-node-2
      - user-shard-1-node-3
    networks:
      - user-storage-network
      - qwik-network

networks:
  user-storage-network:
    driver: bridge